### ISSUE TITLE
Swift Bridging header issue: No Such Module 'React'

### ISSUE THREAD

**Issue by adeb6600** [Kommunicate-io/Kommunicate-React-Native-SDK#2]
React-native-Kommunicate-chat integration for react-native 0.63.2 fails with a Swift compiler error 
```No Such Module React```
Suggestions are needed on a updated path to integration for the latest react-native-version

**Comment by mukeshthawani** [comment]
@adeb6600 can you share a screenshot of Xcode where you are getting this error?
Also, please share the version of `RNKommunicateChat` pod.
