### ISSUE TITLE
Security Error while updating Release Bundle in Play Store for Android Side

### ISSUE THREAD

**Issue by amrit220399** [Kommunicate-io/Kommunicate-React-Native-SDK#28]
Getting Unsafe Cipher Mode Error for the code used in one of the Jar Files in Kommunicate SDK

The file name is : **_com.applozic.mobicommons.encryption.EncryptionUtils.java_**

According to the Google Security Policy , the Cipher instance made using "AES/ECB/NoPadding" should be replaced with “AES/GCM/NoPadding”

Reference Link: [https://support.google.com/faqs/answer/10046138]

**Comment by amrit220399** [comment]
![Screenshot from 2022-09-15 18-36-59](https://user-images.githubusercontent.com/54773165/190412917-bce5e232-45c3-4de9-947c-c0d226167011.png)

**Comment by amntoppo** [comment]
Hey @amrit220399 , We are aware of this issue and we are working on this. It will be finished by end of Quarter 4.
Also, this only comes up as a warning, you will still be able to publish the app.

**Comment by amrit220399** [comment]
Ok it's great then!
