### ISSUE TITLE
change navigation bar text color to black and hide bot name in received message 

### ISSUE THREAD

**Issue by mohamed-ikram** [Kommunicate-io/Kommunicate-React-Native-SDK#6]
i have already added applozic-settings.json in asset folder in android how to change the navigation bar text to black color and hide bot name in received message

**Comment by reytum** [comment]
@mohamed-ikram These settings are not available to customize from the applozic-settings.json file.
The toolbar color can be changed by changing the theme color from the dashboard app widget settings.
Changing the color will change the complete theme of the app.
Currently, we do not have setting to hide the bot name in the received message.

**Comment by mohamed-ikram** [comment]
ok thanks for response....in navigation bar the font color is always is it possible to change it to black 
<img width="359" alt="Kommunicate_Interface" src="https://user-images.githubusercontent.com/62332326/92155439-060eaa80-ee45-11ea-9aa3-8dad58e9866b.png">
